# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0f47a1148ce06b48e4a81887562c64862c2b1d37b93b6062c01facd280132a4e5d019eaa9022dc466e65578dce2c77ce633e735f7ef26668b51836684d4b127

test:
  secret_key_base: 0092acc3c00fc5337e941288e4289ecaf14286a68c0a136ca6a9817a72788bfbca3c00405d74cdc647a46dd4208fd503b739b117c3fbfa892f4f9b89155b84eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
